SELECT [Stock]
	  ,[Date]
      ,[Open]
      ,[High]
      ,[Low]
      ,[Close]
      ,[Adj Close]
      ,[Volume]
      ,[Adj_Open]
      ,[Adj_High]
      ,[Adj_Low]
      ,[Adj_Volume]
      ,[Norm_Adj_Close]
      ,[Norm_Adj_High]
      ,[Norm_Adj_Low]
      ,[Norm_Adj_Open]
      ,[Norm_Adj_Volume]
   FROM [SOS].[dbo].[StockData]
 

 SELECT count(*)
      ,[Stock]
   FROM [SOS].[dbo].[StockData]
   group by [Stock]
   order by [Stock]
